name: "Build Nix package and deploy"

on:
  push:

jobs:
  export-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Building Linux
        run: nix build .#linux64 --print-build-logs --no-sandbox

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: result
        
  export-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Building Windows
        run: nix build .#windows64 --print-build-logs --no-sandbox
        
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: result
          
  export-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Building Web
        run: nix build .#web --print-build-logs --no-sandbox

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: result

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: result